DELETE http://localhost:3001/api/notes/5
###
GET http://localhost:3001/api/notes/
###
POST http://localhost:3001/api/notes/
content-type: application/json

{
    "content": "Digital",
    "important":true 
}

###
PUT http://localhost:3001/api/notes/10
content-type: application/json

{
    "content": "Simulation and modelling",
    "important":false 
}

